name: OnVersionTag

on:
  push:
    tags:
      - '*'
jobs:
  windows:
    
    strategy:
      matrix:
        configuration: [ Release ]
    runs-on: windows-latest

    env:
      Solution_Name: MsMeeseeks.DIE.sln
      
    steps:
    - uses: actions/checkout@main
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3.0.3
      with:
        dotnet-version: 6.0.406
    - run: set DOTNET_CLI_TELEMETRY_OPTOUT=1
    - name: Install dependencies
      run: dotnet restore .\MsMeeseeks.DIE.sln
    - name: Build
      run: dotnet build .\MsMeeseeks.DIE.sln --configuration Release --no-restore
    - name: Publish to NuGet
      uses: brandedoutcast/publish-nuget@master
      with:
        PROJECT_FILE_PATH: Main/Main.csproj
        VERSION_FILE_PATH: Directory.Build.props
        TAG_COMMIT: false
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
